language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install unittest2
# command to run tests
script: python ./Test/pytest.py
# Test only the master
branches:
  only: 
    - master
